# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-release:
    if: github.repository_owner == 'znley'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version and release status
        id: get_version
        run: |
          echo "get version"
          echo "skip_workflow=true" >> $GITHUB_OUTPUT
          exit 0

      - name: Build Binary
        if: steps.get_version.outputs.skip_workflow != 'true'
        run: |
          echo "build binary"
